# Generated by Django 4.2.6 on 2023-11-17 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(max_length=1000)),
                ('genero', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=50)),
                ('año_lanzamiento', models.DateField()),
                ('duracion', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=1000)),
                ('popularidad', models.PositiveSmallIntegerField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('id_pelicula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movieRecommender.pelicula')),
                ('id_plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movieRecommender.plataforma')),
            ],
            options={
                'ordering': ('id_plataforma', 'id_pelicula'),
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='movieRecommender.plataforma'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='movieRecommender.Puntuacion', to='movieRecommender.plataforma'),
        ),
    ]
