# Generated by Django 4.2.7 on 2023-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='pais',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais',
            field=models.ManyToManyField(to='movieRecommender.pais'),
        ),
    ]
