# Generated by Django 4.2.6 on 2023-11-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0002_rename_popularidad_plataforma_numero_producciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='año_lanzamiento',
            new_name='fecha_lanzamiento',
        ),
    ]
