# Generated by Django 4.2.6 on 2023-11-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0003_rename_año_lanzamiento_pelicula_fecha_lanzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_lanzamiento',
            field=models.PositiveIntegerField(),
        ),
    ]
