# Generated by Django 4.2.7 on 2023-12-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommender', '0005_director_generos_remove_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='puntuaciones',
        ),
        migrations.DeleteModel(
            name='Puntuacion',
        ),
    ]
